Repository cohostai/lixinft-be, pull requests merged in 2022-01, with the labels that each got.

#4 feat: ✨ add entities
  src/common/enums/campaign-status.enum.ts
  src/common/enums/index.ts
  src/common/enums/member-status.enum.ts
  src/common/enums/payment-status.enum.ts
  src/common/enums/template-pos.enum.ts
  src/common/enums/template-status.enum.ts
  src/entities/campaign-member.entity.ts
  src/entities/campaign.entity.ts
  src/entities/index.ts
  src/entities/template.entity.ts
Labels: enhancement

#6 feat: ✨ add guard and middleware for authentication
  package.json
  src/app.module.ts
  src/common/decorators/current-user-address.decorator.ts
  src/common/decorators/current-user.decorator.ts
  src/common/decorators/index.ts
  src/common/guards/auth.guard.ts
  src/common/guards/index.ts
  src/common/index.ts
  src/common/middleware/auth.middleware.ts
  src/common/middleware/index.ts
  src/resolvers/posts.resolver.ts
  yarn.lock
Labels: good first issue

#9 feat: ✨ api create campaign and template
  .github/workflows/main.yml
  src/common/middleware/auth.middleware.ts
  src/common/pipes/validation.pipe.ts
  src/dtos/campaigns/create.dto.ts
  src/dtos/campaigns/get.dto.ts
  src/dtos/campaigns/index.ts
  src/dtos/index.ts
  src/dtos/templates/create.dto.ts
  src/dtos/templates/get.dto.ts
  src/dtos/templates/index.ts
  src/dtos/templates/template-response.dto.ts
  src/dtos/users/signup.dto.ts
  src/entities/campaign.entity.ts
  src/entities/index.ts
  src/repositories/campaign.repository.ts
  src/repositories/index.ts
  src/repositories/template.repository.ts
  src/resolvers/campaign.resolver.ts
  src/resolvers/index.ts
  src/resolvers/template.resolver.ts
  src/services/campaign.service.ts
  src/services/index.ts
  src/services/template.service.ts
  src/shared/mail/index.ts
Labels: good first issue

#8 feat: ✨ setup commitlint for commit convention
  .commitlintrc.json
  package.json
  yarn.lock
Labels: enhancement

#11 feat: ⚡ added api get me
  src/resolvers/user.resolver.ts
Labels: good first issue

#10 feat: ⚡ add resolve fields in campaigns
  src/common/middleware/auth.middleware.ts
  src/dtos/campaigns/campaign-response.dto.ts
  src/dtos/campaigns/index.ts
  src/repositories/campaign.repository.ts
  src/resolvers/campaign.resolver.ts
Labels: good first issue

#13 ci: 👷 update web3 token version to 0.2.6
  .github/workflows/main.yml
  package.json
  src/app.module.ts
  src/common/enums/index.ts
  src/common/enums/upload-folder.enum.ts
  src/configs/file-uploader/index.ts
  src/configs/index.ts
  src/controllers/file.controller.ts
  src/controllers/index.ts
  src/environments.ts
  src/services/index.ts
  src/services/s3.service.ts
  yarn.lock
Labels: bug

#17 feat: ✨ api get campaign
  .github/workflows/main.yml
  src/common/decorators/current-user-address.decorator.ts
  src/dtos/users/signup.dto.ts
  src/resolvers/campaign.resolver.ts
  src/resolvers/user.resolver.ts
  src/services/user.service.ts
Labels: good first issue

#19 feat: ✨ api join, approve campaign
  src/dtos/campaign-members/approve-member.dto.ts
  src/dtos/campaign-members/index.ts
  src/dtos/index.ts
  src/repositories/campaign-member.repository.ts
  src/repositories/index.ts
  src/resolvers/campain-member.resolver.ts
  src/resolvers/index.ts
  src/services/campaign-member.service.ts
  src/services/index.ts
Labels: good first issue

#20 feat: ✨ resolve campaign fields
  src/repositories/campaign-member.repository.ts
  src/resolvers/campaign.resolver.ts
  src/resolvers/campain-member.resolver.ts
Labels: good first issue
